development:
  adapter: postgresql
  encoding: unicode
  database: test_site_developement
  pool: 5
  username: mnachaze
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: test_site_test
  pool: 5
  username: mnachaze
  password: 

production:
  adapter: postgresql
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
